version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  convert-Part:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Jupyter get HTML
          command: |
            jupyter nbconvert —execute —to html Part.ipynb

      - store_artifacts:
          path: ./Part.html

workflows:
  main:
    jobs:
      - convert-Part
